### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by tud** [bohnman/squiggly-filter-jackson#6]
Hello,

I'm using Spring Boot and I'd like to achieve this:
I've several RestControllers and I'd like to use Squiggly only if the user adds "?fields=id,code" to URL (it works) otherwise I'd like to have the default behavior i.e. no filter

The problem is that when the user use a filter with some fields, these fields are used through ALL RestControllers from that time :-(
Is it possible to filter objects just on demand and for that particular case not setting for all?

thanks

my code:
SquigglyConfiguration.java

public class SquigglyConfiguration {
	@Bean
    public ObjectMapper objectMapper() {
        return Squiggly.init(new ObjectMapper(), new RequestSquigglyContextProvider());
    }

	@Bean
	public FilterRegistrationBean squigglyRequestFilter() {
		FilterRegistrationBean filter = new FilterRegistrationBean();
		filter.setFilter(new SquigglyRequestFilter());
		filter.setOrder(1);
		return filter;
	}
}

BoxResource.java

@GetMapping
	public ResponseEntity<Page<Box>> findAll(@RequestParam(value = "fields", required = false) String fields, Pageable pageable) {
		log.debug("> box.findAll");
		
		Page<Box> boxes = boxService.findAll(pageable);
		if (null == boxes) {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
		
		if (!StringUtils.isBlank(fields)) {
			String filter = "content{" + fields + "}";
			Squiggly.init(objectMapper, filter);
		}

		log.debug("< box.findAll");
		return new ResponseEntity<>(boxes, HttpStatus.OK);
	}

**Comment by bohnman** [comment]
Actually, the real problem, is the following code in BoxResource.java

```java
if (!StringUtils.isBlank(fields)) {
    String filter = "content{" + fields + "}";
    Squiggly.init(objectMapper, filter);
}
```

You only want to initialize Squiggly once during application startup and the init method that takes a filter string, which is really meant for testing or just trying Squiggly out.

However, I do see that you want to wrap the fields with content{} when the response is a Page object.  To do this, you can use a hook method in RequestSquigglyContextProvider.

Here's how to fix it:

SquigglyConfiguration.java

```
public class SquigglyConfiguration {

    @Bean
    public ObjectMapper objectMapper() {
        return Squiggly.init(new ObjectMapper(), new RequestSquigglyContextProvider() {
            @Override
            protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
                if (!StringUtils.isBlank(fields) && Page.class.isAssignableFrom(beanClass)) {
                    filter = "content{" + filter + "}";
                }

                return filter;
            }
        });
    }

    @Bean
    public FilterRegistrationBean squigglyRequestFilter() {
        FilterRegistrationBean filter = new FilterRegistrationBean();
        filter.setFilter(new SquigglyRequestFilter());
        filter.setOrder(1);
        return filter;
    }
}
```

BoxResource.java

```java
@GetMapping
public ResponseEntity<Page> findAll(Pageable pageable) {
    log.debug("> box.findAll");

    Page<Box> boxes = boxService.findAll(pageable);
    
    if (null == boxes) {
        return new ResponseEntity<>(HttpStatus.NOT_FOUND);
    }

    log.debug("< box.findAll");
    return new ResponseEntity<>(boxes, HttpStatus.OK);
}
```

Let me know if this works for you.

**Comment by tud** [comment]
Thanks for your answer but I'm not able to let it work :-(

this is the configuration

public class SquigglyConfiguration {
	@Bean
	public ObjectMapper objectMapper() {
		return Squiggly.init(new ObjectMapper(), new RequestSquigglyContextProvider() {
			@Override
			protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
				System.out.println("====> customizeFilter");
				if (request.getParameterMap().containsKey("fields") && Page.class.isAssignableFrom(beanClass)) {
					filter = "content{" + filter + "}";
				}
				System.out.println("filter="+filter);
				return filter;
			}
		});
	}

	@Bean
	public FilterRegistrationBean squigglyRequestFilter() {
		FilterRegistrationBean filter = new FilterRegistrationBean();
		filter.setFilter(new SquigglyRequestFilter());
		filter.setOrder(1);
		return filter;
	}
}

and the box resource

@GetMapping
	public ResponseEntity<Page<Box>> findAll(Pageable pageable) {
		log.debug("> box.findAll");

		Page<Box> boxes = boxService.findAll(pageable);
		if (null == boxes) {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}

		log.debug("< box.findAll");
		return new ResponseEntity<>(boxes, HttpStatus.OK);
	}

it looks like that the customizeFilter is never called

thanks

**Comment by bohnman** [comment]
Are you sure that your objectMapper() method of the SquigglyConfiguration class is getting called?  Do you need to annotate that class with @Configuration?

**Comment by bohnman** [comment]
If that doesn't work.  Try annotating annotating the objectMapper() method with @Primary like so:

```java
@Bean
@Primary
public ObjectMapper objectMapper() {
    return Squiggly.init(new ObjectMapper(), new RequestSquigglyContextProvider() {
        @Override
        protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
            if (!StringUtils.isBlank(fields) && Page.class.isAssignableFrom(beanClass)) {
                filter = "content{" + filter + "}";
            }

            return filter;
        }
    });
}
```

**Comment by tud** [comment]
you are right. I forgot @Configuration :flushed: or better, the second time I deleted it...
now I've another problem:
some fields of the ResponseEntity are lazy loaded and I receive an exception about it
any idea how I can solve this problem?

org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: failed to lazily initialize a collection of role: domain.Project.boxes, could not initialize proxy - no Session (through reference chain: org.springframework.data.domain.PageImpl["content"]->java.util.Collections$UnmodifiableRandomAccessList[0]->domain.Project["boxes"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: failed to lazily initialize a collection of role: domain.Project.boxes, could not initialize proxy - no Session (through reference chain: org.springframework.data.domain.PageImpl["content"]->java.util.Collections$UnmodifiableRandomAccessList[0]->domain.Project["boxes"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:292)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:231)
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:203)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.github.bohnman.squiggly.web.SquigglyRequestFilter.doFilter(SquigglyRequestFilter.java:35)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: failed to lazily initialize a collection of role: domain.Project.boxes, could not initialize proxy - no Session (through reference chain: org.springframework.data.domain.PageImpl["content"]->java.util.Collections$UnmodifiableRandomAccessList[0]->domain.Project["boxes"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:343)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFieldsFiltered(BeanSerializerBase.java:751)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase._serializeWithObjectId(BeanSerializerBase.java:610)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:148)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:704)
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.serializeAsField(SquigglyPropertyFilter.java:313)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFieldsFiltered(BeanSerializerBase.java:743)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:153)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1429)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:951)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:285)
	... 112 common frames omitted
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: domain.Project.boxes, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:582)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:145)
	at org.hibernate.collection.internal.PersistentSet.size(PersistentSet.java:143)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:102)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:704)
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.serializeAsField(SquigglyPropertyFilter.java:313)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFieldsFiltered(BeanSerializerBase.java:743)
	... 125 common frames omitted

**Comment by bohnman** [comment]
can you post your pom.xml?

**Comment by tud** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>cesp</groupId>
	<artifactId>CESP</artifactId>
	<version>0.0.2-SNAPSHOT</version>
	<packaging>jar</packaging>

	<inceptionYear>2017</inceptionYear>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.1.RELEASE</version>
		<relativePath /> 
	</parent>

	<prerequisites>
		<maven>${maven.version}</maven>
	</prerequisites>

	<properties>
		<argLine>-Djava.security.egd=file:/dev/./urandom -Xmx256m</argLine>
		<mave.version>3.0.0</mave.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<hibernate.version>5.2.7.Final</hibernate.version>
		<commons-io.version>2.5</commons-io.version>
		<commons-lang.version>3.5</commons-lang.version>
		<logstash-logback-encoder.version>4.8</logstash-logback-encoder.version>
		<swagger.version>2.6.1</swagger.version>
		<jhipster.server.version>1.0.4</jhipster.server.version>
		<oracle.version>12.1.0.2</oracle.version>
		<squiggly-filter-jackson.version>1.1.2</squiggly-filter-jackson.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-envers</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>${commons-lang.version}</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons-io.version}</version>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>${logstash-logback-encoder.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-hibernate5</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-hppc</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-json-org</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
			<version>1</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-data</artifactId>
		</dependency>
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>tools</artifactId>
					<groupId>com.sun</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.oracle.jdbc</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>${oracle.version}</version>
		</dependency>
		<dependency>
			<groupId>javax.cache</groupId>
			<artifactId>cache-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.ehcache</groupId>
			<artifactId>ehcache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-jcache</artifactId>
			<version>${hibernate.version}</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>${swagger.version}</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>${swagger.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.jhipster</groupId>
			<artifactId>jhipster</artifactId>
			<version>${jhipster.server.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.bohnman</groupId>
			<artifactId>squiggly-filter-jackson</artifactId>
			<version>${squiggly-filter-jackson.version}</version>
		</dependency>
	</dependencies>

	
	<repositories>
		<repository>
			<id>maven.oracle.com</id>
			<name>oracle-maven-repo</name>
			<url>https://maven.oracle.com</url>
			<layout>default</layout>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</releases>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by bohnman** [comment]
OK.  I haven't used hibernate/JPA with Spring Boot, but you could try using OpenEntityManagerInViewFilter instead of the default OpenEntityManagerInViewInterceptor.

To do this:

1) Disable the OpenEntityManagerInViewInterceptor, by setting the following property in your application configuration

```
spring.jpa.open-in-view=false
```

2) Add the OpenEntityManagerInViewFilter, making sure that it is ordered **before** the squiggly filter.

```java
@Bean
public FilterRegistrationBean openEntityManagerInViewFilter() {
    FilterRegistrationBean filter = new FilterRegistrationBean();
    filter.setFilter(new OpenEntityManagerInViewFilter());
    filter.setOrder(0);
    return filter;
}
```

**Comment by tud** [comment]
I don't want to use OpenEntityManagerInViewFilter, it's supposed to be an antipattern :-(
https://vladmihalcea.com/2016/05/30/the-open-session-in-view-anti-pattern/

**Comment by tud** [comment]
I'm using this module https://github.com/FasterXML/jackson-datatype-hibernate to manage hibernate with jackson

**Comment by bohnman** [comment]
Do you always get this exception or only when you specify the fields parameter on the query string?

**Comment by tud** [comment]
always
just calling an api

**Comment by bohnman** [comment]
Did you look at this thread?

https://github.com/FasterXML/jackson-datatype-hibernate/issues/25

**Comment by tud** [comment]
yes, but it's closed and not using your library I don't have any issue
I can retrieve the whole object without loading children

this is my json with postman for api/boxes

{
  "content": [
    {
      "id": 375,
      "createdBy": "xxxx",
      "createdDate": "2016-06-29T20:47:02.675+02:00",
      "lastModifiedDate": "2016-06-29T22:48:25.828+02:00",
      "owner": "user1@company1.com",
      "code": "BA-000489",
      "enoviaId": "48925.21818.3824.29138",
      "lastPromotedBy": "user1@company1.com",
      "lastPromotedDate": "2016-06-29T22:48:25.806+02:00",
      "lastPromotedUp": true,
      "status": "In Work",
      "project": null,
      "sectionBoxes": null,
      "approvals": null,
      "parts": null,
      "documents": null,
      "cads": null
    },
.....

where null fields are the lazy load ones

**Comment by bohnman** [comment]
OK.  I think what you are saying is that you want squiggly to ignore introspecting fields that are lazy-loaded proxies so they don't cause session exception.   I'll need to think about how to best implement this and I'll comment on this issue when I a fix (should be within the next couple of days).

**Comment by bohnman** [comment]
Wait.   I think I've got it!

You are not registering the Hibernate5Module with the ObjectMapper

```java
@Bean
@Primary
public ObjectMapper objectMapper() {
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.registerModule(new new Hibernate5Module());
    return Squiggly.init(objectMapper, new RequestSquigglyContextProvider() {
        @Override
        protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
            if (!StringUtils.isBlank(fields) && Page.class.isAssignableFrom(beanClass)) {
                filter = "content{" + filter + "}";
            }

            return filter;
        }
    });
}
```

**Comment by tud** [comment]
you are right!!

I'm using this code for auto discovery all modules

```
@Configuration
@Primary
public class SquigglyConfiguration {
	
	@Bean
	public ObjectMapper objectMapper() {
		ObjectMapper objectMapper = new ObjectMapper().findAndRegisterModules();
		return Squiggly.init(objectMapper, new RequestSquigglyContextProvider() {
			@Override
			protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
				if (request.getParameterMap().containsKey("fields") && Page.class.isAssignableFrom(beanClass)) {
					filter = "content{" + filter + "}";
				}
				return filter;
			}
		});
	}

	@Bean
	public FilterRegistrationBean squigglyRequestFilter() {
		FilterRegistrationBean filter = new FilterRegistrationBean();
		filter.setFilter(new SquigglyRequestFilter());
		filter.setOrder(1);
		return filter;
	}
}

```
thank you very much for your help!!

**Comment by bohnman** [comment]
No problem.  Closing issue.
